// auto generated by misoapi v0.2.2-beta.3 at 2025/07/07 10:33:47 (CST), please do not modify
package api

import (
	"github.com/curtisnewbie/miso/middleware/dbquery"
	"github.com/curtisnewbie/miso/miso"
)

func init() {
	miso.HttpPost("/api/v1", miso.AutoHandler(
		func(inb *miso.Inbound, req PostReq) (PostRes, error) {
			return api1(inb, req)
		})).
		Extra(miso.ExtraName, "api1")

	miso.HttpPost("/api/v2", miso.AutoHandler(
		func(inb *miso.Inbound, req *PostReq) (PostRes, error) {
			return api2(inb, req)
		})).
		Extra(miso.ExtraName, "api2")

	miso.HttpPost("/api/v3", miso.AutoHandler(
		func(inb *miso.Inbound, req *PostReq) (*PostRes, error) {
			return api3(inb, req)
		})).
		Extra(miso.ExtraName, "api3")

	miso.HttpPost("/api/v4", miso.AutoHandler(
		func(inb *miso.Inbound, req ApiReq) (*PostRes, error) {
			return api4(inb, req)
		})).
		Extra(miso.ExtraName, "api4")

	miso.HttpPost("/api/v5", miso.AutoHandler(
		func(inb *miso.Inbound, req *ApiReq) (*PostRes, error) {
			return api5(inb, req)
		})).
		Extra(miso.ExtraName, "api5")

	miso.HttpPost("/api/v6", miso.AutoHandler(
		func(inb *miso.Inbound, req *ApiReq) (*PostRes, error) {
			return api6(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api6")

	miso.HttpPost("/api/v7", miso.AutoHandler(
		func(inb *miso.Inbound, req *ApiReq) (ApiRes, error) {
			return api7(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api7")

	miso.HttpPost("/api/v8", miso.AutoHandler(
		func(inb *miso.Inbound, req *ApiReq) (*ApiRes, error) {
			return api8(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api8")

	miso.HttpPost("/api/v9", miso.AutoHandler(
		func(inb *miso.Inbound, req *ApiReq) (*[]ApiRes, error) {
			return api9(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api9")

	miso.HttpPost("/api/v10", miso.AutoHandler(
		func(inb *miso.Inbound, req *ApiReq) ([]ApiRes, error) {
			return api10(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api10")

	miso.HttpPost("/api/v11", miso.AutoHandler(
		func(inb *miso.Inbound, req *ApiReq) ([]PostRes, error) {
			return api11(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api11")

	miso.HttpPost("/api/v12", miso.AutoHandler(
		func(inb *miso.Inbound, req []ApiReq) ([]PostRes, error) {
			return api12(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api12")

	miso.HttpPost("/api/v13", miso.AutoHandler(
		func(inb *miso.Inbound, req []ApiReq) (any, error) {
			return api13(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api13")

	miso.HttpPost("/api/v14", miso.AutoHandler(
		func(inb *miso.Inbound, req ApiReq) ([]PostRes, error) {
			return api14(inb, req, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api14")

	miso.HttpGet("/api/v15", miso.ResHandler(
		func(inb *miso.Inbound) ([]PostRes, error) {
			return api15(inb, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api15")

	miso.HttpGet("/api/v16", miso.ResHandler(
		func(inb *miso.Inbound) (miso.PageRes[PostRes], error) {
			return api16(inb, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api16").
		Extra(miso.ExtraNgTable, true)

	miso.HttpGet("/api/v17", miso.ResHandler(
		func(inb *miso.Inbound) ([]PostRes, error) {
			return api17(inb, dbquery.GetDB()), nil
		})).
		Extra(miso.ExtraName, "api17")

	miso.HttpPost("/api/v18", miso.ResHandler(
		func(inb *miso.Inbound) (any, error) {
			api18(inb, dbquery.GetDB())
			return nil, nil
		})).
		Extra(miso.ExtraName, "api18")

	miso.HttpGet("/api/v19", miso.ResHandler(
		func(inb *miso.Inbound) (any, error) {
			return nil, api19(inb, dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api19")

	miso.HttpPost("/api/v20", miso.AutoHandler(
		func(inb *miso.Inbound, req ApiReq) (any, error) {
			api20(inb, req, dbquery.GetDB())
			return nil, nil
		})).
		Extra(miso.ExtraName, "api20")

	miso.HttpPost("/api/v21", miso.RawHandler(
		func(inb *miso.Inbound) {
			var req ApiReq
			inb.MustBind(&req)
			api21(inb, req, dbquery.GetDB())
		})).
		DocJsonReq(ApiReq{}).
		Extra(miso.ExtraName, "api21")

	miso.HttpPost("/api/v22", miso.RawHandler(
		func(inb *miso.Inbound) {
			var req ApiReq
			inb.MustBind(&req)
			api22(inb, req, dbquery.GetDB())
		})).
		DocJsonReq(ApiReq{}).
		DocJsonResp(PostRes{}).
		Extra(miso.ExtraName, "api22")

	miso.HttpPost("/api/v23", miso.RawHandler(api23)).
		DocJsonResp(PostRes{}).
		Extra(miso.ExtraName, "api23")

	miso.HttpPost("/api/v24", miso.RawHandler(
		func(inb *miso.Inbound) {
			api24(inb, inb.Rail(), dbquery.GetDB())
		})).
		Extra(miso.ExtraName, "api24")

	miso.HttpPost("/api/v25", miso.RawHandler(
		func(inb *miso.Inbound) {
			api25(inb, inb.Rail(), dbquery.GetDB())
		})).
		DocJsonResp(PostRes{}).
		Extra(miso.ExtraName, "api25")

	miso.HttpOptions("/api/v26", miso.RawHandler(api26)).
		Extra(miso.ExtraName, "api26")

	miso.HttpHead("/api/v27", miso.RawHandler(api27)).
		Extra(miso.ExtraName, "api27")

	miso.HttpPatch("/api/v28", miso.RawHandler(api28)).
		Extra(miso.ExtraName, "api28")

	miso.HttpConnect("/api/v29", miso.RawHandler(api29)).
		Extra(miso.ExtraName, "api29")

	miso.HttpTrace("/api/v30", miso.RawHandler(api30)).
		Extra(miso.ExtraName, "api30")

	miso.HttpPost("/api/v31", miso.AutoHandler(
		func(inb *miso.Inbound, req EmptyReq) (any, error) {
			return nil, api31(inb, req)
		})).
		Extra(miso.ExtraName, "api31")

}
