// auto generated by misoapi v0.1.4-beta.3 at 2024/07/20 21:33:43, please do not modify
package main

import (
	"github.com/curtisnewbie/miso/demo/api"
	"github.com/curtisnewbie/miso/middleware/mysql"
	"github.com/curtisnewbie/miso/miso"
)

func init() {
	miso.IPost("/api/v1",
		func(inb *miso.Inbound, req PostReq) (PostRes, error) {
			return api1(inb, req)
		})
	miso.IPost("/api/v2",
		func(inb *miso.Inbound, req *PostReq) (PostRes, error) {
			return api2(inb, req)
		})
	miso.IPost("/api/v3",
		func(inb *miso.Inbound, req *PostReq) (*PostRes, error) {
			return api3(inb, req)
		})
	miso.IPost("/api/v4",
		func(inb *miso.Inbound, req api.ApiReq) (*PostRes, error) {
			return api4(inb, req)
		})
	miso.IPost("/api/v5",
		func(inb *miso.Inbound, req *api.ApiReq) (*PostRes, error) {
			return api5(inb, req)
		})
	miso.IPost("/api/v6",
		func(inb *miso.Inbound, req *api.ApiReq) (*PostRes, error) {
			return api6(inb, req, mysql.GetMySQL())
		})
	miso.IPost("/api/v7",
		func(inb *miso.Inbound, req *api.ApiReq) (api.ApiRes, error) {
			return api7(inb, req, mysql.GetMySQL())
		})
	miso.IPost("/api/v8",
		func(inb *miso.Inbound, req *api.ApiReq) (*api.ApiRes, error) {
			return api8(inb, req, mysql.GetMySQL())
		})
}
